#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

vmware-user-suid-wrapper &

feh --bg-fill /home/alcode/Desktop/wallpapers/archkali.png &

bash ~/.config/polybar/./launch.sh --blocks &

picom --config ~/.config/picom/picom.conf &


wmname LG3D &

bspc config border_width 0

xrandr --output Virtual1 --mode 1920x1080
